export const POST_ACTIVE_ELECTION_DATA = "POST_ACTIVE_ELECTION_DATA";
export const ELECTIONS_LOADING = 'ELECTIONS_LOADING';
export const ELECTION_LOAD_SUCCESS = 'ELECTION_LOAD_SUCCESS';
export const POST_ELECTION = 'POST_ELECTION';


