export const ELECTIONS_LOADING = 'ELECTIONS_LOADING';
export const ELECTION_LOAD_SUCCESS = 'ELECTION_LOAD_SUCCESS';
export const POST_ELECTION = 'POST_ELECTION';
export const GET_ELECTION_MODULE = 'GET_ELECTION_MODULE';
export const POST_CALL_ELECTION = 'POST_CALL_ELECTION';
export const POST_CALL_ELECTION_DATA = 'POST_CALL_ELECTION_DATA';
export const SET_CALL_ELECTION_DATA = 'SET_CALL_ELECTION_DATA';
export const ELECTION_REVIEW_DATA = 'ELECTION_REVIEW_DATA';
export const ON_ELECTION_APPROVAL_CHANGE = 'ON_ELECTION_APPROVAL_CHANGE';
export const SNACK_BAR_MESSAGE_LOADED = 'SNACK_BAR_MESSAGE_LOADED';


export const APPROVAL_STATE = {
    APPROVE: 'APPROVE',
    REJECT: 'REJECT',
    PENDING: 'PENDING',
  };










